clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
steps:
  - name: make version
    image: dart:stable
    commands:
      - ./make_version.sh
  - name: pub release
    image: dart:stable
    secrets: [ PAT_SECRET_PACKAGE ]
    commands:
      - dart pub token add https://git.mrcyjanek.net/api/packages/mrcyjanek/pub/ --env-var=PAT_SECRET_PACKAGE
      - dart pub publish --skip-validation
